#cloud-config
groups:
  - ubuntu: [root,sys]
  - developer

users:
  - default
  - name: michael
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh_import_id:
      - gh:mikelv702


runcmd:
  - sudo apt-get update
  - sudo apt install fail2ban -q -y
  - sudo systemctl enable fail2ban
  - sudo systemctl start fail2ban
  - wget -qO- https://repos-droplet.digitalocean.com/install.sh | sudo bash
  