# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MIT

#cloud-config
groups:
  - ubuntu: [root,sys]
  - developer

# Add users to the system. Users are added after groups are added.
users:
  - default
  # - name: terraform
  #   gecos: terraform
  #   shell: /bin/bash
  #   primary_group: hashicorp
  #   sudo: ALL=(ALL) NOPASSWD:ALL
  #   groups: users, admin
  #   lock_passwd: false
  #   ssh_authorized_keys:
  #     - # Paste your created SSH key here

runcmd:
  - sudo apt-get update
  - sudo apt install fail2ban -q -y
  - sudo systemctl enable fail2ban
  - sudo systemctl start fail2ban
  - wget -qO- https://repos-droplet.digitalocean.com/install.sh | sudo bash
  